# Generated by Django 5.2.17 on 2026-08-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Основной адрес",
                        max_length=120,
                        verbose_name="название",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=180, verbose_name="получатель"),
                ),
                ("phone", models.CharField(max_length=40, verbose_name="телефон")),
                ("city", models.CharField(max_length=120, verbose_name="город")),
                ("street", models.CharField(max_length=180, verbose_name="улица")),
                ("house", models.CharField(max_length=40, verbose_name="дом")),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="квартира/офис"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="индекс"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="комментарий"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=True, verbose_name="адрес по умолчанию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлен"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес покупателя",
                "verbose_name_plural": "адреса покупателей",
                "ordering": ["-is_default", "-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("user",),
                        name="one_default_address_per_user",
                    )
                ],
            },
        ),
    ]
