# Generated by Django 5.2.17 on 2026-08-23 09:56

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="название")),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлена"),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220, verbose_name="название")),
                (
                    "slug",
                    models.SlugField(max_length=240, unique=True, verbose_name="slug"),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name="артикул",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=280, verbose_name="краткое описание"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="старая цена",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="остаток"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="на главной"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлен"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": ["category__sort_order", "category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=catalog.models.product_image_upload_to,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="alt-текст"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="главное изображение"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение товара",
                "verbose_name_plural": "изображения товаров",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="название")),
                ("value", models.CharField(max_length=260, verbose_name="значение")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика",
                "verbose_name_plural": "характеристики",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
