# Generated by Django 5.2.17 on 2026-08-25 17:22

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                max_length=255,
                upload_to=catalog.models.product_image_upload_to,
                verbose_name="изображение",
            ),
        ),
    ]
