# Generated by Django 5.2.17 on 2026-09-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=80, verbose_name="штрихкод"),
        ),
        migrations.AddField(
            model_name="product",
            name="ozon_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="ссылка на Ozon"
            ),
        ),
    ]
