# Generated by Django 5.2.17 on 2026-08-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="фамилия"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(max_length=40, verbose_name="телефон")),
                ("city", models.CharField(max_length=120, verbose_name="город")),
                ("address", models.CharField(max_length=260, verbose_name="адрес")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="индекс"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="комментарий"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("confirmed", "Подтвержден"),
                            ("processing", "В обработке"),
                            ("shipped", "Передан в доставку"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="статус заказа",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("refunded", "Возвращен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="статус оплаты",
                    ),
                ),
                (
                    "shipment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает передачи"),
                            ("in_transit", "В пути"),
                            ("ready_for_pickup", "Готов к выдаче"),
                            ("delivered", "Доставлен"),
                        ],
                        default="pending",
                        max_length=24,
                        verbose_name="статус доставки",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="сумма"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлен"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=220, verbose_name="название товара"),
                ),
                (
                    "product_sku",
                    models.CharField(blank=True, max_length=80, verbose_name="артикул"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена за шт."
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="количество")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "позиция заказа",
                "verbose_name_plural": "позиции заказа",
            },
        ),
    ]
