# Generated by Django 5.2.17 on 2026-08-23 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("yookassa", "ЮKassa"),
                            ("mock", "Локальная тестовая оплата"),
                        ],
                        default="yookassa",
                        max_length=24,
                        verbose_name="провайдер",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="id платежа у провайдера",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("waiting_for_capture", "Ожидает подтверждения"),
                            ("succeeded", "Успешно"),
                            ("canceled", "Отменен"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="статус",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="валюта"
                    ),
                ),
                (
                    "confirmation_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="ссылка на оплату"
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="ключ идемпотентности",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ответ провайдера"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="оплачен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлен"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "платеж",
                "verbose_name_plural": "платежи",
                "ordering": ["-created_at"],
            },
        ),
    ]
