# Generated by Django 5.2.17 on 2026-08-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("cdek", "СДЭК"),
                            ("mock", "Локальная тестовая доставка"),
                        ],
                        default="cdek",
                        max_length=24,
                        verbose_name="провайдер",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("courier", "Курьером"), ("pickup", "Пункт выдачи")],
                        default="courier",
                        max_length=24,
                        verbose_name="способ доставки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает передачи"),
                            ("registered", "Зарегистрирована"),
                            ("in_transit", "В пути"),
                            ("ready_for_pickup", "Готова к выдаче"),
                            ("delivered", "Доставлена"),
                            ("canceled", "Отменена"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="статус",
                    ),
                ),
                ("tariff_code", models.PositiveIntegerField(verbose_name="код тарифа")),
                (
                    "from_city_code",
                    models.PositiveIntegerField(verbose_name="город отправления"),
                ),
                (
                    "to_city",
                    models.CharField(max_length=120, verbose_name="город получателя"),
                ),
                (
                    "to_city_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="код города получателя"
                    ),
                ),
                (
                    "recipient_address",
                    models.CharField(max_length=260, verbose_name="адрес доставки"),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=40, verbose_name="телефон получателя"),
                ),
                (
                    "delivery_point",
                    models.CharField(blank=True, max_length=80, verbose_name="код ПВЗ"),
                ),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="стоимость доставки",
                    ),
                ),
                (
                    "period_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="срок от, дней"
                    ),
                ),
                (
                    "period_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="срок до, дней"
                    ),
                ),
                (
                    "cdek_uuid",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="uuid СДЭК"
                    ),
                ),
                (
                    "cdek_number",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="номер СДЭК"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="трек-номер"
                    ),
                ),
                (
                    "raw_request",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="запрос в СДЭК"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ответ СДЭК"
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="зарегистрирована"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлена"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "доставка",
                "verbose_name_plural": "доставки",
                "ordering": ["-created_at"],
            },
        ),
    ]
